### PR TITLE
fixed memory gains while each iteration

### PR DESCRIPTION
**Pull request by inhereanya**

### CODE REVIEW

**Comment by bozkayasalihx** [comment]
@inhereanya! could you explain changes in detail pls :)

**Comment by inhereanya** [comment]
> @inhereanya! could you explain changes in detail pls :)

for sure, each iteration you did, was creating new pointer in mem which not for memory management

**Comment by inhereanya** [comment]
> > @inhereanya! could you explain changes in detail pls :)
> 
> for sure, each iteration you did, was creating new pointer in mem which not for memory management

@bozkayasalihx, ofc more performant too 💯

**Review by bozkayasalihx — APPROVED** [review]
why did you changed declations without being intialized

**Review by inhereanya — COMMENTED** [review]
@bozkayasalihx, because not need to init declations at the begining. its also saves from mems

**Comment by bozkayasalihx** [comment]
@inhereanya, sound reasonable, i'll merge it soon 👍

**Pull request merged**
